### ISSUE TITLE
 i find the engine in IOS system run 10 times slower than which in Andriod system

### ISSUE THREAD

**Issue by changelee82** [student-t/Stockfish-iOS-8#2]
there is a question about the Stockfish8 I want to ask:
I load Stockfish8 both in Android and IOS system, and set search depth as 12. Then i find the engine in IOS system run 10 times slower than which in Andriod system.

Could you please tell me What can I do to fix this if you know ? Thanks a lot !

**Comment by student-t** [comment]
Q: How do you know it's 10 times slower? What about the hardware? Are we talking about simulator?

**Comment by student-t** [comment]
PS: You are very welcome to grab the source code for the project and publish it to the App Store. It has the latest Stockfish engine.

**Comment by changelee82** [comment]
Thank you so much for your reply. I have found the solution for the problem. I made a misake to use debug model to compile SF8 instead of release model. 

Again, thank you so much for your help.
